sudo: false
language: tex

branches:
    only:
        - master

addons:
    apt:
        packages:
            - texlive-full

script:
    - latexmk -pdf ClassicThesis.tex

notification:
    email:
        recipients:
            - junktogo@web.de
        on_success: change
        on_failure: always
